name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Eleventy
      - name: Install dependencies
        run: npm ci

      # Build do Eleventy
      - name: Build the site
        run: npm run build

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: jamesives/github-pages-deploy-action@v4.6.8  # Versão atualizada
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Diretório de saída do Eleventy
          publish_branch: gh-pages  # Branch de destino
